@startsalt
{#
{* File | Edit | Source | Move | Manual | Refactor 
 Refactor | New | Open File | - | Close | Close All }
     {
    header
    }
    {#
        {T
        +menu1
        ++submenu11
        ++submenu12
        +menu2
        ++submenu21
        ++submenu22
        }{
            
            {/    tab1 | tab2 | tab3    }
            {+
            input  | . | "input-text" 
            textbox| . | {+
            This is text box. 
            You can write double several lines here.
            } | *
            check  | . | (X) check1   | ( ) check2 
            radio  | . | [X] radio1   | [ ] radio2 
            combo  | . | ^select^
            button | . | [button]
            }
        }
    }
    {
    footer
    }
}
@endsalt